from typing import List
from datetime import datetime, timedelta
from s2python.frbc import FRBCInstruction


class S2FrbcInstructionProfile:
    """Instruction profile for FRBC device control.

    Contains FRBCInstruction objects that tell the device which operation modes
    to use at each timestep. Instructions are derived from the optimized plan
    and specify actuator configurations with operation mode IDs and factors.

    This class represents a profile generated by the planning algorithm as a
    list of S2 FRBCInstruction objects that can be sent to the device.

    Attributes:
        profile_start: Start time of the instruction profile
        timestep_duration: Duration of each timestep
        elements: List of FRBCInstruction objects, one per timestep/actuator
    """

    def __init__(
        self,
        profile_start: datetime,
        timestep_duration: timedelta,
        elements: List[FRBCInstruction],
    ):
        self.profile_start = profile_start
        self.timestep_duration = timestep_duration
        self.elements = elements

    def __str__(self) -> str:
        return f"S2FrbcInstructionProfile(elements={self.elements})"
