from typing import List
from datetime import datetime, timedelta
from s2python.frbc import FRBCInstruction


class S2FrbcInstructionProfile:
    # This class represents a profile generated by the Reflex as a list of
    # S2 FRBCInstruction s
    def __init__(
        self,
        profile_start: datetime,
        timestep_duration: timedelta,
        elements: List[FRBCInstruction],
    ):
        self.profile_start = profile_start
        self.timestep_duration = timestep_duration
        self.elements = elements

    def __str__(self) -> str:
        return f"S2FrbcInstructionProfile(elements={self.elements})"
